FROM node:22-alpine

WORKDIR /app

# Copiar package.json y package-lock.json
COPY package*.json ./

# Instalar dependencias
RUN npm install

# Copiar el resto del código
COPY . .

# Exponer el puerto
EXPOSE 4000

# Añadir el flag --host para que escuche en todas las interfaces de red
CMD ["npm", "run", "dev", "--", "--host"]
