name: Sync Fork with Upstream

on:
  schedule:
    - cron: '0 * * * *' # Runs every hour
  workflow_dispatch: # Allows manual trigger

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout target repo
        uses: actions/checkout@v3
        with:
          ref: staging # Checkout your fork's staging branch
          fetch-depth: 0 # Fetch all history for all branches and tags

      - name: Configure Git
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'

      - name: Add Upstream Remote
        run: git remote add upstream https://github.com/Andersson1712/Futurar.git

      - name: Fetch Upstream
        run: git fetch upstream

      - name: Merge Upstream Staging
        run: |
          git merge upstream/staging --no-edit

      - name: Push to Fork
        run: git push origin staging
